### PR TITLE
Feature/selector optimization

### PR DESCRIPTION
**Pull request by bobnik**
This PR is a selector cleanup effort. In some cases, our selectors are overly broad in their selection, resulting in unnecessary recalculation. I fixed some of the more obvious cases. There are a number of places where we still do expensive calculations repeatedly, and I could not figure out how to resolve. One such issue is the mix of connected Redux components and a useSelector hook (due to Konva interaction). As I do not anticipate refactoring to remove this hybrid approach any time soon, I expect we can live with some inefficiency.

I was unable to observe a visible increase in performance when using the UI. That said, I was concerned about the unlikely possibility of _slowing things down_. I tested with a large import and it felt about the same. Obviously, please do your own spot testing.

### CODE REVIEW

**Comment by jeffeb3** [comment]
The line connecting layers seems to be missing in this branch.

**Comment by jeffeb3** [comment]
I can't find anything else different from the testing, and the code looks good to me.

**Comment by bobnik** [comment]
> The line connecting layers seems to be missing in this branch.

Ah, you're right. An oversight, and worse, I don't know how to fix. I'll revisit later and let you know.

**Comment by bobnik** [comment]
Will resubmit this as a separate PR.

**Pull request closed without merging**
