### PR TITLE
Feature/gcode input

### PR DESCRIPTION
**Pull request by jeffeb3**
### GCode Input

Similar to the thr input, this will import a gcode file and use the vertices as the source to generate either a gcode or thr output.

### Motivation

The main benefit of this (for thr and gcode users) is to be able to bring in, and somewhat manipulate the patterns generated for gcode. They can be made in inkscape, for a plotter, with CAM software, or even sandify.

### TODO
x The language on the Import page focuses on .thr files. I think the copyright info is good, and I hope we can keep it. I do not know of any good repositories for gcode patterns, but I am happy to link those there too.
x More importantly, the discussion in #113 about where the input pattern lives would be good to get resolved.

### Verification
There is a .gcode file I put in the pattern_input folder. It has some lines and arcs. It looks good, but was manually generated, so of course, I did the arcs the way I thought they should be done. But then I grabbed an arc torture test from the v1engineering forums, and it turned out correct looking too.

This solves issue #62

### CODE REVIEW

**Comment by jeffeb3** [comment]
I solved #113 in this PR by looking at the state.file.name in the machine and about tabs. If it isn't empty, then I use the vertices from the import. If it is, then I use the transformVertices, from the shapes. That doesn't have the stickyness of the "last tab" hack, but it doesn't give you a way to easily clear the state if you've imported something either. So we may have to revisit this in the future.

I think this is ready to go.

**Comment by jeffeb3** [comment]
Rebased.

**Comment by jeffeb3** [comment]
@bobnik Do you have any thoughts on this PR?

**Comment by bobnik** [comment]
> @bobnik Do you have any thoughts on this PR?

Looks good to me. I tried 5 different random files I found on the web, and they all imported well. As mentioned, I don't know much about this format.

**Pull request merged**
