### PR TITLE
rotate until the "pattern" is complete

### PR DESCRIPTION
**Pull request by bobnik**
This PR is a response to #130. To produce more pleasing art, when _a/b_ is a non-integer, will rotate _b_ times. I also made the two variables whole numbers instead of decimals. That makes it easier to replicate the examples on the Wolfram Alpha pages.

The shapes now produce quite different results than before with some values. My opinion is that this is an improvement and that shapes that need extra rotations look odd when they cannot complete. That said, it _is_ a change and I'm not sure if we need to worry about this?

### CODE REVIEW

**Comment by jeffeb3** [comment]
Doesn't it often repeat before b? Should we try b/2 and b/3 or something?

I was going to suggest this same change though. I think it is good.

**Comment by bobnik** [comment]
> Doesn't it often repeat before b? Should we try b/2 and b/3 or something?

Yes, you are right. I'll push a fix later. I also am trying to get the shape to stay a constant normalized size (so that starting size is the only parameter you have to fiddle with)

**Comment by bobnik** [comment]
The npm test check failed, but it seems to be because it is trying to run the skipped "App.test.js" spec. Not sure why this is happening...

**Comment by jeffeb3** [comment]
Weird. That test came from the original example I started with (create-react-app). I like the idea of that test, but there's no reason to keep it if it doesn't work, and this PR is not breaking it (it is just broken). So if you don't want to fix it, I'm fine removing it.

**Comment by bobnik** [comment]
> Weird. That test came from the original example I started with (create-react-app). I like the idea of that test, but there's no reason to keep it if it doesn't work, and this PR is not breaking it (it is just broken). So if you don't want to fix it, I'm fine removing it.

I went ahead and fixed the spec, and also the react-ga warning we were getting.

**Pull request merged**
