### PR TITLE
npm test ran in github.

### PR DESCRIPTION
**Pull request by jeffeb3**

### CODE REVIEW

**Comment by jeffeb3** [comment]
This is a work in progress, but I have to have a PR to really test this.

**Comment by Allted** [comment]
Busy beaver.....getting exciting

**Comment by jeffeb3** [comment]
OK. No longer a WIP. I think this is actually working to do this:
- run npm test, and only succeed if those tests pass. All PRs should be tested after this gets to master.
- run the test with npm versions 8, 10, 12. The deploy will be in 12, so that is probably what I should install locally.
- If I make a release, it triggers the Deploy workflow. I have only tested this so far with a dummy deploy step, but I think this will work when we are ready to deploy 0.2.1. I fully expect to need to fix something when I try to make a release, and it fails to run.

**Comment by jeffeb3** [comment]
Sorry for the extra tags and releases. I had to make a release to test the action.

**Pull request merged**
