### PR TITLE
Feature/function effect

### PR DESCRIPTION
**Pull request by jeffeb3**
This is fun. I was playing with the Custom Warp functions and I created some neat patterns, so I parameterized them and they are even more fun to play with, and harder to mess up.

This star has a 'circle' warp type:
star_warp

This wiper has a 'angle' warp type:
wiper_warp

This square has the 'quad' warp type:
polygon_quad_warp

### CODE REVIEW

**Comment by jeffeb3** [comment]
'grid':

screenshot-2021-01-28-1611870311

**Comment by bobnik** [comment]
@jeffeb3 I don't think this needs to hold up the merge, but I do think x-shear and y-shear should be separate. The visual effect is different for each. The combined shear seems odd to me.

**Comment by jeffeb3** [comment]
I may not have the signs right. But rotating it 90 degrees should be the Y-Shear.

**Comment by bobnik** [comment]
> I may not have the signs right. But rotating it 90 degrees should be the Y-Shear.

Duh. Got it :)

**Pull request merged**
