### PR TITLE
Fix reverse, and fix the gcode to work in the machine's coordinates.

### PR DESCRIPTION
**Pull request by jeffeb3**

### CODE REVIEW

**Comment by Allted** [comment]
What the hell! how did you do that so fast, damn, I am impressed as hell right now.

**Comment by Allted** [comment]
I don't think  reverse is doing anything

**Comment by Allted** [comment]
Can you just have it puke out the code backwards, that would be perfect?

**Comment by jeffeb3** [comment]
I'm pretty sure I fixed it. I verified it on my machine.

It was a problem with the signal, not with the algorithm to reverse it. I just reverse the list of vertices before they turn into text.

**Comment by jeffeb3** [comment]
I noticed that the web page won't refresh if you have it open when I deploy a new copy. You have to shift + F5 it to get the new code from jeffeb3.github.io/sandify.

**Comment by jeffeb3** [comment]
```
G01 X240.000 Y260.000
G01 X260.000 Y260.000
G01 X260.000 Y240.000
G01 X240.000 Y240.000


G01 X240.000 Y240.000
G01 X260.000 Y240.000
G01 X260.000 Y260.000
G01 X240.000 Y260.000
```
That's one with the reverse and one without. One square.

**Comment by Allted** [comment]
I swear I refreshed.....but I refreshed a second time and it works for some crazy reason...My bad sorry.

I just refreshed again and it does work but I am pretty sure regular is reverse and reverse is regular. Am I just a pain in the ass or what?

**Comment by Allted** [comment]
Oh, shoot I get it. You are adding a reverse at the end of the same code!!!! 
I was thinking it was generating an inward path or outward, not both.

If you could separate them you can have it do a pattern in and a different pattern out, that is why I was asking about the center coordinates.

**Comment by jeffeb3** [comment]
I'm not sure what order you're expecting them to be, but this is what I get for the square, with the grow enabled:

```
G01 X240.000 Y240.000
G01 X262.500 Y237.500
G01 X265.000 Y265.000
G01 X232.500 Y267.500
G01 X230.000 Y230.000
G01 X272.500 Y227.500
G01 X275.000 Y275.000
G01 X222.500 Y277.500
G01 X220.000 Y220.000
G01 X282.500 Y217.500
G01 X285.000 Y285.000
G01 X212.500 Y287.500
G01 X210.000 Y210.000
G01 X292.500 Y207.500
G01 X295.000 Y295.000
G01 X202.500 Y297.500
G01 X200.000 Y200.000
G01 X302.500 Y197.500
G01 X305.000 Y305.000
G01 X192.500 Y307.500
G01 X190.000 Y190.000
G01 X312.500 Y187.500
G01 X315.000 Y315.000
G01 X182.500 Y317.500
G01 X180.000 Y180.000
G01 X322.500 Y177.500
G01 X325.000 Y325.000
G01 X172.500 Y327.500
G01 X170.000 Y170.000
G01 X332.500 Y167.500
G01 X335.000 Y335.000
G01 X162.500 Y337.500
G01 X160.000 Y160.000
G01 X342.500 Y157.500
G01 X345.000 Y345.000
G01 X152.500 Y347.500
G01 X150.000 Y150.000
G01 X352.500 Y147.500
G01 X355.000 Y355.000
G01 X142.500 Y357.500
```

Which looks like it's starting small, and growing.

**Comment by jeffeb3** [comment]
No, I'm only doing reverse or forward. The code isn't very complicated:

```
    if (this.props.reverse) {
      lines.reverse();
    }
```

**Comment by jeffeb3** [comment]
I'm really just reordering the vertices if the reverse is selected.

**Comment by Allted** [comment]
Okay, I will run them in the morning. I trust you have it right.

I can't believe this, I am very envious of your skill set. Absolutely impressed at this thing. I will run some patterns take some pics. This is pretty seriously polished already.

**Comment by jeffeb3** [comment]
Well, we all have our strengths. I take a few hours to make a table in CAD and then it doesn't even fit together. Software engineering is just a tool, like a lot of other types of engineering. You can use it for anything and the more you practice, the better you get. I have been practicing for 12 years, as my full-time job, with co workers that were already experts. That helps.

Also, most of the polish comes from the tools. I haven't ever done web development as a job, but I dabble in it every few years, and every few years, I find that the state-of-the-art has just made it so much better to work with. If you can believe it, I was in the Internet club in middle school, and we didn't even have css, it was all html. Then I did some CSS, and thought that was great, then I did some javascript, and thought it sucked, then I tried jquery, and thought it was great, but still confusing, and css still didn't work quite right. React and Redux and React-components are all just super slick.

**Comment by jeffeb3** [comment]
Did you get a chance to try any of the patterns over the weekend?

**Comment by Allted** [comment]
Dam laser....Loading up an SD card right now. Sorry for lagging

**Pull request merged**
